k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  logBufferSize: 1000
  logRequestSize: 200
  currentContext: minikube
  currentCluster: minikube
  fullScreenLogs: false
  clusters:
    minikube:
      namespace:
        active: default
        favorites:
        - all
        - default
      view:
        active: pods
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70

