gui:
  sidePanelWidth: 0.2
  theme:
    activebordercolor:
    - white
    - bold
quitOnTopLevelReturn: false
reporting: "off"
startupPopupVersion: 1
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
